from yacs.config import CfgNode as CN


_C = CN()

_C.DATASET = CN()
_C.DATASET.DATASET_DIR = 'CE-Net/dataset/DRIVE'
_C.DATASET.NUM_CLASSES = 1
_C.DATASET.IN_CHANNELS = 3
_C.DATASET.IMAGE_SIZE = (512, 512)

_C.AUGMENT = CN()
_C.AUGMENT.HUE_SATURATION_VALUE = True
_C.AUGMENT.HUE_SATURATION_VALUE_PROBABILITY = 0.5
_C.AUGMENT.SHIFT_SCALE_ROTATE = True
_C.AUGMENT.SHIFT_SCALE_ROTATE_PROBABILITY= 0.5
_C.AUGMENT.HORIZONTAL_FLIP = True
_C.AUGMENT.HORIZONTAL_FLIP_PROBABILITY = 0.5
_C.AUGMENT.VERTICAL_FLIP = True
_C.AUGMENT.VERTICAL_FLIP_PROBABILITY = 0.5
_C.AUGMENT.ROTATE = True
_C.AUGMENT.ROTATE_PROBABILITY = 0.5

_C.DDRNET = CN()
_C.DDRNET.BLOCK = 'Basic'
_C.DDRNET.LAYERS = [2, 2, 2, 2]
_C.DDRNET.PLANES = 32
_C.DDRNET.SPP_PLANES = 128
_C.DDRNET.HEAD_PLANES = 64

_C.TRAIN = CN()
_C.TRAIN.DEVICE = 'cuda'
_C.TRAIN.USE_PRETRAINED_WEIGHTS = True
_C.TRAIN.PRETRAINED_WEIGHTS_DIR = '../weights/DDRNet23s_imagenet.pth'
_C.TRAIN.OUTPUT_WEIGHTS_DIR = '../weights/'
_C.TRAIN.TRAIN_BATCH_SIZE = 3
_C.TRAIN.NUM_WORKERS = 1
_C.TRAIN.TOTAL_EPOCH = 300
_C.TRAIN.INITAL_EPOCH_LOSS = 100000
_C.TRAIN.LEARNING_RATE = 2e-4
_C.TRAIN.LR_DECAY_PATIENCE = 10
_C.TRAIN.LR_DECAY_FACTOR = 0.5

_C.VALIDATION = CN()
_C.VALIDATION.VAL_BATCH_SIZE = 5
_C.VALIDATION.NUM_WORKERS = 1

_C.TEST = CN()
_C.TEST.DEVICE = 'cuda'
_C.TEST.NUM_WORKERS = 1
_C.TEST.IMAGE_SIZE = (512, 512)

_C.LOSS_FUNCTION = CN()
_C.LOSS_FUNCTION.NAME = 'BCEWithLogits'
_C.LOSS_FUNCTION.POS_CLASS_WEIGHT = 0.9136878125

def get_cfg():
  return _C.clone()
