DATASET:
  DATASET_DIR: 'dataset/DRIVE'
  NUM_CLASSES: 1
  IN_CHANNELS: 3
  IMAGE_SIZE: (512, 512)

AUGMENT:
  HUE_SATURATION_VALUE: True
  HUE_SATURATION_VALUE_PROBABILITY: 0.5
  SHIFT_SCALE_ROTATE: True
  SHIFT_SCALE_ROTATE_PROBABILITY: 0.5
  HORIZONTAL_FLIP: True
  HORIZONTAL_FLIP_PROBABILITY: 0.5
  VERTICAL_FLIP: True
  VERTICAL_FLIP_PROBABILITY: 0.5
  ROTATE: True
  ROTATE_PROBABILITY: 0.5

DDRNET:
  BLOCK: 'Basic' #Basic or Bottleneck
  LAYERS: [2, 2, 2, 2]
  PLANES: 32
  SPP_PLANES: 128
  HEAD_PLANES: 64

TRAIN:
  DEVICE: 'cuda'
  USE_PRETRAINED_WEIGHTS: True
  PRETRAINED_WEIGHTS_DIR: 'weights/DDRNet23s_imagenet.pth'
  OUTPUT_WEIGHTS_DIR: 'weights'
  TRAIN_BATCH_SIZE: 2
  NUM_WORKERS: 1
  TOTAL_EPOCH: 300
  INITAL_EPOCH_LOSS: 100000
  LEARNING_RATE: 2e-4
  LR_DECAY_PATIENCE: 10
  LR_DECAY_FACTOR: 0.5

VALIDATION:
  VAL_BATCH_SIZE: 1
  NUM_WORKERS: 1

TEST:
  DEVICE: 'cuda'
  NUM_WORKERS: 1
  IMAGE_SIZE: (512, 512)

LOSS_FUNCTION:
  NAME: 'BCELoss' #BCELoss or DiceLoss
  POS_CLASS_WEIGHT: 0.9136878125 #If BCELoss is chosen

